import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:flutter/foundation.dart';

class DatabaseRepository {
  static Database? _database;

  /// Lazily initializes the database connection singleton.
  static Future<Database> get database async {
    if (_database != null) return _database!;
    _database = await _initDB();
    return _database!;
  }

  /// Establishes a connection to the SQLite file generated by the native layer.
  static Future<Database> _initDB() async {
    // The database name must mirror the Kotlin DatabaseHelper configuration exactly.
    String dbPath = join(await getDatabasesPath(), 'tracking_session.db');

    return await openDatabase(
      dbPath,
      // We do not define an onCreate callback here, as the schema is strictly managed by Kotlin.
    );
  }

  /// Retrieves the localized telemetry payload, ordered chronologically.
  static Future<List<Map<String, dynamic>>> fetchTelemetryLog() async {
    try {
      final db = await database;
      return await db.query('locations', orderBy: 'timestamp DESC');
    } catch (e) {
      if (kDebugMode) {
        print("SYSTEM METRIC: Disk Read Failure - $e");
      }
      return [];
    }
  }
}
